const canvasWidth = 1280;
const canvasHeight = 720;

const swordImg = new Image();
swordImg.src = './img/sword.png';
const swordSwingImg = new Image();
swordSwingImg.src = './img/swordSwing.png';
const autoSwordImg = new Image();
autoSwordImg.src = './img/autoSword.png';
const swordRangeImg = new Image();
swordRangeImg.src = './img/swordRange.png';
const heartImg = new Image();
heartImg.src = './img/heart.png';
const coinImg = new Image();
coinImg.src = './img/coin.png';
const shardImg = new Image();
shardImg.src = './img/shard.png';
const gemImg = new Image();
gemImg.src = './img/gem.png';
const fastFeetImg = new Image();
fastFeetImg.src = './img/fastFeet.png';
const armorImg = new Image();
armorImg.src = './img/armor.png';
const xpImg = new Image();
xpImg.src = './img/xp.png';

//Setup upgrades
let upgrades = {
  damage_1: {
    id: 'damage_1',
    name: 'Sharper Sword',
    image: swordImg,
    description: '+1 Melee Damage',
    baseCost: 1,
    costMultiplier: 1.5,
    cost: 1,
    costType: 'gold',
    level: 0,
    maxLevel: 7,
    effect: { stat: 'meleeDamage', value: 1, type: 'add' },
    purchased: false,
    x: canvasWidth / 2,
    y: canvasHeight / 2,
    parents: [],
    connections: ['swingSpeed_1', 'maxHealth_1', 'cursorPickup', 'attackRange_1'],
  },
  swingSpeed_1: {
    id: 'swingSpeed_1',
    name: 'Sword Swing Speed',
    image: swordSwingImg,
    description: '+7% Melee attack speed',
    baseCost: 30,
    costMultiplier: 1.2,
    cost: 30,
    costType: 'gold',
    level: 0,
    maxLevel: 7,
    effect: { stat: 'attackInterval', value: -0.07, type: 'multiply' },
    purchased: false,
    x: canvasWidth / 2 + 127,
    y: canvasHeight / 2,
    parents: ['damage_1'],
    connections: ['damage_2'],
  },
  maxHealth_1: {
    id: 'maxHealth_1',
    name: 'Healthier',
    image: heartImg,
    description: '+20 Max Health',
    baseCost: 2,
    costMultiplier: 1.5,
    cost: 2,
    costType: 'gold',
    level: 0,
    maxLevel: 8,
    effect: { stat: 'maxHealth', value: 20, type: 'add' },
    purchased: false,
    x: canvasWidth / 2,
    y: canvasHeight / 2 - 127,
    parents: ['damage_1'],
    connections: ['armor_1', 'moveSpeed_1', 'maxHealth_2'],
  },
  cursorPickup: {
    id: 'cursorPickup',
    name: 'Cursor Pickup',
    image: coinImg,
    description: '+1 Mouse Loot Pickup',
    baseCost: 1,
    costMultiplier: 1,
    cost: 1,
    costType: 'shards',
    level: 0,
    maxLevel: 1,
    effect: { stat: 'cursorLootMult', value: 1, type: 'multiply' },
    purchased: false,
    x: canvasWidth / 2 - 127,
    y: canvasHeight / 2,
    parents: ['damage_1'],
    connections: ['autoAttack'],
  },
  armor_1: {
    id: 'armor_1',
    name: 'Reinforced',
    image: armorImg,
    description: '+1 Armor',
    baseCost: 1,
    costMultiplier: 1.5,
    cost: 1,
    costType: 'gold',
    level: 0,
    maxLevel: 10,
    effect: { stat: 'armor', value: 1, type: 'add' },
    purchased: false,
    x: canvasWidth / 2 - 127,
    y: canvasHeight / 2 - 254,
    parents: ['maxHealth_1'],
    connections: [],
  },
  moveSpeed_1: {
    id: 'moveSpeed_1',
    name: 'Fast Feet',
    image: fastFeetImg,
    description: '+10% Move Speed',
    baseCost: 10,
    costMultiplier: 1.6,
    cost: 10,
    costType: 'gold',
    level: 0,
    maxLevel: 5,
    effect: { stat: 'moveSpeed', value: 0.1, type: 'multiply' },
    purchased: false,
    x: canvasWidth / 2,
    y: canvasHeight / 2 - 254,
    parents: ['maxHealth_1'],
    connections: [],
  },
  autoAttack: {
    id: 'autoAttack',
    name: 'Auto Attack',
    image: autoSwordImg,
    description: 'Auto Attack Enemies',
    baseCost: 1,
    costMultiplier: 1,
    cost: 1,
    costType: 'shards',
    level: 0,
    maxLevel: 1,
    effect: { stat: 'autoAttack', value: true, type: 'set' },
    purchased: false,
    x: canvasWidth / 2 - 254,
    y: canvasHeight / 2 + 127,
    parents: ['cursorPickup'],
    connections: ['enemyGold'],
  },
  enemyGold: {
    id: 'enemyGold',
    name: 'Gold Greed',
    image: coinImg,
    description: '+1 Gold From Enemies',
    baseCost: 1,
    costMultiplier: 1,
    cost: 1,
    costType: 'shards',
    level: 0,
    maxLevel: 1,
    effect: { stat: 'enemyGold', value: 1, type: 'add' },
    purchased: false,
    x: canvasWidth / 2 - 381,
    y: canvasHeight / 2,
    parents: ['autoAttack'],
    connections: ['gemChance', 'xpGain_1'],
  },
  damage_2: {
    id: 'damage_2',
    name: 'Honed Blade',
    image: swordImg,
    description: '+4 Melee Damage',
    baseCost: 100,
    costMultiplier: 1.2,
    cost: 100,
    costType: 'gold',
    level: 0,
    maxLevel: 10,
    effect: { stat: 'meleeDamage', value: 4, type: 'add' },
    purchased: false,
    x: canvasWidth / 2 + 254,
    y: canvasHeight / 2 + 127,
    parents: ['swingSpeed_1'],
    connections: [],
  },
  attackRange_1: {
    id: 'attackRange_1',
    name: 'Extended Reach',
    image: swordRangeImg,
    description: '+30 Melee Range',
    baseCost: 100,
    costMultiplier: 1.2,
    cost: 100,
    costType: 'gold',
    level: 0,
    maxLevel: 5,
    effect: { stat: 'attackRange', value: 30, type: 'add' },
    purchased: false,
    x: canvasWidth / 2,
    y: canvasHeight / 2 + 127,
    parents: ['damage_1'],
    connections: [],
  },
  gemChance: {
    id: 'gemChance',
    name: 'Gem Miner',
    image: gemImg,
    description: '+10% Gem Drop Chance',
    baseCost: 100,
    costMultiplier: 2,
    cost: 100,
    costType: 'shards',
    level: 0,
    maxLevel: 2,
    effect: { stat: 'gemChance', value: 1.1, type: 'multiply' },
    purchased: false,
    x: canvasWidth / 2 - 508,
    y: canvasHeight / 2 + 127,
    parents: ['enemyGold'],
    connections: [],
  },
  xpGain_1: {
    id: 'xpGain',
    name: 'Quick Learner',
    image: xpImg,
    description: '+20% XP Gained',
    baseCost: 25,
    costMultiplier: 1.5,
    cost: 25,
    costType: 'gems',
    level: 0,
    maxLevel: 5,
    effect: { stat: 'xpGain', value: 1.2, type: 'multiply' },
    purchased: false,
    x: canvasWidth / 2 - 381,
    y: canvasHeight / 2 - 127,
    parents: ['enemyGold'],
    connections: [],
  },
  maxHealth_2: {
    id: 'maxHealth_2',
    name: 'Vigor',
    image: heartImg,
    description: '+50 Max Health',
    baseCost: 20,
    costMultiplier: 1.5,
    cost: 20,
    costType: 'gems',
    level: 0,
    maxLevel: 5,
    effect: { stat: 'maxHealth', value: 50, type: 'add' },
    purchased: false,
    x: canvasWidth / 2 + 127,
    y: canvasHeight / 2 - 254,
    parents: ['maxHealth_1'],
    connections: [],
  },
};
